name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: "12.16.x"
      - uses: actions/checkout@v2.3.3

      - run: yarn install --silent --frozen-lockfile

      # - run: yarn lint

      - run: yarn test

      - run: yarn build

  changelog:
    needs: [test]
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: etcdigital/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
